### ISSUE TITLE
Error authenticating! Error: Token provided to verifyJWT is missing or not a string ?

### ISSUE THREAD

**Issue by kilaniba** [feathersjs/feathers-authentication-client#73] opened 2017-10-10 06:30 UTC
I work with reactjs frontend. After create my server.js (feathers ) , i try to send my (username and password) to my route post . there is my code .

`axios.post('http://localhost:4200/login',
  {
    strategy: 'local',
    username: 'k0',//self.state.username,
    password:'kk'// self.state.password
  }).then(response => {
    console.log('Authenticated!', response);
  return app.passport.verifyJWT(response.accessToken);
})
.then(payload => {
  console.log('JWT Payload', payload);
  return app.service('users').get(payload.userId);
})
.then(user => {
  app.set('user', user);
  console.log('User', app.get('user'));
})
.catch(function(error){
  console.error('Error authenticating!', error);
})
`
When i click my button , there is my error in console "Error authenticating! Error: Token provided to verifyJWT is missing or not a string".

**Comment by daffl** [comment] 2017-10-10 14:59
Duplicate of https://github.com/feathersjs/feathers-authentication/issues/584

**Closed by daffl** 2017-10-10 14:59 UTC
